### PR TITLE
Query/filter custom reports

### PR DESCRIPTION
**Pull request by jakinyang**
This adds further queries for the filters.

### CODE REVIEW

**Comment by jakinyang** [comment]
This will require more work but I would like to have this merged for now

**Comment by Benjamin0203** [comment]
Nice thank you for the filter queries.

**Review by Bohjaangles — APPROVED** [review]
Looks good Jae!

**Comment by jakinyang** [comment]
I added another commit to the latest version of main

**Review by Benjamin0203 — APPROVED** [review]
Thank you! looks good

**Pull request merged**
