### PR TITLE
--add queries and resolvers for filter queries

### PR DESCRIPTION
**Pull request by jakinyang**
Pull request to merge basic filter queries for many users/reports. Partially addresses issue #21  and issue #20

### CODE REVIEW

**Comment by jakinyang** [comment]
Further implementation will be needed for better filtering as well as better scoping. Check comments on issues #21 , #20 , #19, and #18 for further details of capabilities introduced by Prisma.

**Review by jakinyang — COMMENTED** [review]
The queries work for now, so it seems good to merge.

**Review by jakinyang — COMMENTED** [review]
@Bohjaangles @Benjamin0203 when you can pull this and then you can pull main to have more filter capabilities for the GraphQL api

**Comment by jakinyang** [comment]
I think that it might be possible to not add more queries, but to expand this query and the filter inputs that it can take in order to be more robust: 

i.e. the current filter input only takes in the fields that already exist on a given user, but we could just add custom filter fields:
-- reports
- longitudeGreaterThan (for getting a limited range of geographic values)
- longitudeLessThan (for getting a limited range of geographic values)
- latitudeGreaterThan (for getting a limited range of geographic values)
- latitudeLessThan (for getting a limited range of geographic values)
- statusCategoryIn (for filtering out or filtering for certain kinds of reports)
- reportCategoryIn (for filtering out or filtering for certain kinds of reports)
- createdBefore (for getting or filtering out fresh v. stale reports)
- createdAfter (for getting or filtering out fresh v. stale reports)
- descriptionContains (searching for certain descriptions or data points in report descriptions)

-- users
- firstNameIn
- lastNameIn
- qualificationIn
- phoneNumberContains (potential for getting the area codes of numbers)

While this is not exhaustive, the API should be flexible enough to be expanded upon in the future, and some or all of these examples would be sufficient for the purposes of the current scope of this application.

**Review by Bohjaangles — APPROVED** [review]
Looks good Jae, thanks for doing this!

**Pull request merged**
