### PR TITLE
--add user/report search queries and userfilter queries

### PR DESCRIPTION
**Pull request by jakinyang**
The initial version of userfilterqueries and the revised user/report search queries are working. This should be pulled and I will make another branch to continue working. This address issues #18, #20, #21

### CODE REVIEW

**Comment by jakinyang** [comment]
Thank you for the review guys!

**Comment by Benjamin0203** [comment]
Looks nice! We need the filter functions

**Review by Benjamin0203 — APPROVED** [review]
FIlter queries is nice!

**Review by Bohjaangles — APPROVED** [review]
Good work Jae, this looks good :)

**Pull request merged**
